# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coba2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomePage(object):
    def setupUi(self, Window1):
        Window1.setObjectName("Window1")
        Window1.resize(411, 342)
        self.centralwidget = QtWidgets.QWidget(Window1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 411, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_submit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_submit.setGeometry(QtCore.QRect(180, 240, 71, 23))
        self.btn_submit.setObjectName("btn_submit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 110, 264, 46))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_open_file = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_open_file.setObjectName("btn_open_file")
        self.horizontalLayout.addWidget(self.btn_open_file)
        self.label_nama_file = QtWidgets.QLabel(self.layoutWidget)
        self.label_nama_file.setObjectName("label_nama_file")
        self.horizontalLayout.addWidget(self.label_nama_file)
        self.verticalLayout.addLayout(self.horizontalLayout)
        Window1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 411, 21))
        self.menubar.setObjectName("menubar")
        Window1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window1)
        self.statusbar.setObjectName("statusbar")
        Window1.setStatusBar(self.statusbar)

        self.retranslateUi(Window1)
        QtCore.QMetaObject.connectSlotsByName(Window1)

    def retranslateUi(self, Window1):
        _translate = QtCore.QCoreApplication.translate
        Window1.setWindowTitle(_translate("Window1", "Analisis Sentimen"))
        self.label.setText(_translate("Window1", "ANALISIS SENTIMEN"))
        self.btn_submit.setText(_translate("Window1", "Submit"))
        self.label_2.setText(_translate("Window1", "Pilih Data"))
        self.btn_open_file.setText(_translate("Window1", "Open"))
        self.label_nama_file.setText(_translate("Window1", "Belum ada data terpilih"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window1 = QtWidgets.QMainWindow()
    ui = Ui_WelcomePage()
    ui.setupUi(Window1)
    Window1.show()
    sys.exit(app.exec_())
